name: "Pull Request"

on:
  pull_request:
    branches:
      - main
    paths:
      - bar/**

permissions:
  contents: read

jobs:
  main-job:
    name: Run bar tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Test against bar
        run: |
          cat bar/README.md
