name: "Pull Request"

on:
  pull_request:
    branches:
      - main
    paths:
      - foo/**

permissions:
  contents: read

jobs:
  main-job:
    name: Run foo tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Test against foo
        run: |
          cat foo/README.md
