name: "PR checks"

on:
  pull_request:
    branches:
      - main

jobs:
  changes:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: read
    outputs:
      foo: ${{ steps.filter.outputs.foo }}
      bar: ${{ steps.filter.outputs.bar }}
      markdown: ${{ steps.filter.outputs.markdown }}
      markdown_files: ${{ steps.filter.outputs.markdown_files }}
    steps:
    - uses: dorny/paths-filter@v3
      id: filter
      with:
        list-files: shell
        filters: |
          foo:
            - 'foo/**'
          bar:
            - 'bar/**'
          markdown:
            - added|modified: '**/*.md'

  foo:
    needs: changes
    if: ${{ needs.changes.outputs.foo == 'true' }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Test against foo
        run: |
          grep -i foo foo/code.txt

  bar:
    needs: changes
    if: ${{ needs.changes.outputs.bar == 'true' }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Test against bar
        run: |
          grep -i bar bar/code.txt

  markdown:
    needs: changes
    if: ${{ needs.changes.outputs.markdown == 'true' }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Spellcheck
        uses: rojopolis/spellcheck-github-actions@v0
        with:
          source_files: ${{ needs.changes.outputs.markdown_files }}
          task_name: spellcheck_markdown

  summary:
    needs: [foo, bar, markdown]
    if: always()
    runs-on: ubuntu-latest
    steps:
      - name: Check for failures
        if: contains(needs.*.result, 'failure')
        run: exit 1
